export const COUNTRIES = [
"Albania",
"Algeria",
"Angola",
"Argentina",
"Armenia",
"Australia",
"Austria",
"Azerbaijan",
"Bahrain",
"Bangladesh",
"Barbados",
"Belarus",
"Belgium",
"Belize",
"Bermuda",
"Bolivia",
"Brazil",
"Brunei Darussalam",
"Bulgaria",
"Canada",
"Chile",
"China",
"Chinese Taipei",
"Colombia",
"Costa Rica",
"Croatia",
"Cuba",
"Cyprus",
"Czech Republic",
"Denmark",
"Dominican Republic",
"Ecuador",
"Egypt (Arab Rep.)",
"El Salvador",
"Equatorial Guinea",
"Estonia",
"Eswatini",
"Finland",
"France",
"Gabon",
"Gambia",
"Georgia",
"Germany",
"Greece",
"Grenada",
"Guatemala",
"Guyana",
"Haiti",
"Honduras",
"Hong Kong China",
"Hungary",
"Iceland",
"India",
"Indonesia",
"Iran (Islamic Rep.)",
"Iraq",
"Ireland",
"Italy",
"Jamaica",
"Japan",
"Kazakhstan",
"Korea",
"Kuwait",
"Latvia",
"Libya",
"Lithuania",
"Luxembourg",
"North Macedonia",
"Malaysia",
"Malta",
"Mauritius",
"Mexico",
"Moldova",
"Morocco",
"Myanmar",
"Nepal",
"Netherlands",
"New Zealand",
"Nicaragua",
"Niger",
"Nigeria",
"Norway",
"Oman",
"Panama",
"Papua New Guinea",
"Paraguay",
"Peru",
"Philippines",
"Poland",
"Portugal",
"Qatar",
"Romania",
"Russian Federation",
"Saudi Arabia",
"Singapore",
"Slovakia",
"Slovenia",
"South Africa",
"Spain",
"Sudan",
]

export const COMP_LIMIT_PATH = "data/comp_limit.csv";
export const GLOBAL_CAP_PATH = "data/global_assets.csv";
export const GLOBAL_COMP_PATH = "data/global_comp.csv";
export const TABLE_NAME = "data";
export const PAGE_LIMIT = 10;
export const DB_PATH = "data/countries_data.db";
export const HOST_NAME = "https://assets-assignment-532.onrender.com";
